"""VoiceLedger brain: Amazon Bedrock integration with an offline fallback.

Every money insight is generated by Amazon Bedrock (AWS Builder mini
challenge). When no model is configured or AWS is unreachable, a fully
working rule-based fallback takes over so the demo never breaks.

Offline behaviour is deterministic and covered by tests.
"""

from __future__ import annotations

import json
import logging
from typing import Any

log = logging.getLogger("voiceledger.brain")

CATEGORIES = [
    "groceries", "dining", "transport", "shopping", "utilities",
    "entertainment", "health", "education", "travel", "other",
]

# keyword -> category, weighted by specificity (first match group wins)
_KEYWORDS: list[tuple[str, list[str]]] = [
    ("groceries", ["grocery", "groceries", "supermarket", "bigbasket", "blinkit", "zepto",
                   "vegetable", "sabzi", "milk", "kirana", "dmart", "reliance fresh",
                   "instamart", "fruits", "ration"]),
    ("dining", ["restaurant", "dinner", "lunch", "breakfast", "swiggy", "zomato", "cafe",
                "coffee", "pizza", "chai", "bakery", "dominos", "kfc", "food", "brunch",
                "dhaba", "biryani", "dosa"]),
    ("transport", ["cab", "uber", "ola", "taxi", "metro", "bus", "train", "petrol",
                   "fuel", "parking", "auto", "rickshaw", "fastag", "toll"]),
    ("shopping", ["amazon", "flipkart", "myntra", "clothes", "shirt", "shoes", "mall",
                  "electronics", "phone", "laptop", "watch", "ajio", "nykaa"]),
    ("utilities", ["electricity", "water bill", "gas", "internet", "wifi", "broadband",
                   "mobile", "recharge", "rent", "bill", "dth", "cylinder"]),
    ("entertainment", ["movie", "cinema", "netflix", "spotify", "game", "concert",
                       "bookmyshow", "hotstar", "prime video", "party"]),
    ("health", ["doctor", "hospital", "pharmacy", "medicine", "gym", "apollo",
                "clinic", "dentist", "lab test"]),
    ("education", ["course", "tuition", "udemy", "coursera", "exam", "school fee",
                   "college", "book purchase"]),
    ("travel", ["hotel", "flight", "oyo", "makemytrip", "trip", "vacation",
                "airbnb", "yatra", "railway booking"]),
]


def offline_categorize(note: str) -> str:
    """Rule-based expense categorizer. Deterministic, no network needed."""
    text = (note or "").lower()
    for category, keywords in _KEYWORDS:
        if any(kw in text for kw in keywords):
            return category
    return "other"


class Brain:
    """Bedrock-backed categorizer + insights with offline fallback."""

    def __init__(self, model_id: str = "", region: str = "ap-south-1") -> None:
        self.model_id = model_id.strip()
        self.region = region
        self._client = None  # created lazily so import never needs AWS

    # -- Bedrock plumbing ------------------------------------------------
    def _bedrock_client(self):
        if self._client is not None:
            return self._client
        if not self.model_id:
            raise RuntimeError("BEDROCK_MODEL_ID is not set")
        import boto3  # local import: offline mode never touches boto3
        self._client = boto3.client("bedrock-runtime", region_name=self.region)
        return self._client

    def _converse(self, system: str, prompt: str, max_tokens: int = 300) -> str:
        client = self._bedrock_client()
        resp = client.converse(
            modelId=self.model_id,
            system=[{"text": system}],
            messages=[{"role": "user", "content": [{"text": prompt}]}],
            inferenceConfig={"maxTokens": max_tokens, "temperature": 0.2},
        )
        return "".join(
            block.get("text", "")
            for block in resp["output"]["message"]["content"]
        ).strip()

    @property
    def bedrock_available(self) -> bool:
        """True only if a model is configured AND a call actually works."""
        if not self.model_id:
            return False
        try:
            self._converse("You are a health check.", "Reply with exactly: ok", 10)
            return True
        except Exception as exc:  # noqa: BLE001 - any AWS failure -> fallback
            log.warning("Bedrock unavailable, using offline fallback: %s", exc)
            return False

    # -- categorization --------------------------------------------------
    def categorize(self, note: str, amount: float) -> tuple[str, str]:
        """Return (category, source) where source is 'bedrock' or 'offline'."""
        try:
            text = self._converse(
                "You classify personal expenses. Reply with exactly one word: "
                f"one of {', '.join(CATEGORIES)}.",
                f'Classify this expense of {amount}: "{note}"',
                max_tokens=20,
            ).lower().strip().strip('".,')
            if text in CATEGORIES:
                return text, "bedrock"
            log.warning("Bedrock returned unknown category %r; falling back", text)
        except Exception as exc:  # noqa: BLE001
            log.info("Bedrock categorize failed (%s); using offline rules", exc)
        return offline_categorize(note), "offline"

    # -- insights --------------------------------------------------------
    def insights(self, summary: dict[str, Any], budgets: list[dict[str, Any]]) -> tuple[str, str]:
        """Return (insight_text, source). Voice-first: 2-3 short sentences."""
        try:
            context = json.dumps({"summary": summary, "budgets": budgets})
            text = self._converse(
                "You are a friendly voice finance assistant. Reply in 2 to 3 short "
                "spoken sentences, no markdown, no lists: name the top spending "
                "categories, note any trend or anomaly, and give exactly one "
                "actionable money-saving tip.",
                f"Here is this month's spending data: {context}",
                max_tokens=300,
            )
            if text:
                return text, "bedrock"
        except Exception as exc:  # noqa: BLE001
            log.info("Bedrock insights failed (%s); using offline template", exc)
        return self._offline_insights(summary, budgets), "offline"

    @staticmethod
    def _offline_insights(summary: dict[str, Any], budgets: list[dict[str, Any]]) -> str:
        total = summary.get("total_expense", 0)
        by_cat = summary.get("by_category", {})
        if total <= 0:
            return "You haven't logged any spending this month yet. Log an expense and I'll keep track of it for you."
        top = max(by_cat.items(), key=lambda kv: kv[1])
        over = [b for b in budgets if b.get("over")]
        if over:
            worst = over[0]
            return (
                f"So far this month you've spent {int(total)} rupees, mostly on "
                f"{top[0]} at {int(top[1])} rupees. You're over budget on "
                f"{worst['category']} by {int(worst['spent'] - worst['budget'])} rupees. "
                f"Try cutting one {worst['category']} outing a week to get back on track."
            )
        return (
            f"So far this month you've spent {int(total)} rupees, mostly on "
            f"{top[0]} at {int(top[1])} rupees. You're within all your budgets. "
            f"Nice going. Keep logging and I'll warn you before you overspend."
        )
